title:              Muestrario Tres Arroyos
email:              isecundaria107@gmail.com
description:        Muestrario de proyectos escolares Tres Arroyos
author:             Inspección Secundaria 107
baseurl:            "/MuestrarioSecundaria"
url:                "https://shalsh33.github.io/"

# Social Profiles
twitter_username:   escuelas_secundarias_3_arroyos
github_username:    
facebook_username:  
instagram_username:  escuelas_secundarias_3_arroyos
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
